### ISSUE TITLE
Build dev it is really not working at all

### ISSUE THREAD

**Issue by MichelDiz** [VenusProtocol/venus-protocol-interface#47]
I'm trying to follow the docs(readme) and doing my stuff to try to run this repo. But no luck. Not on macOS, no luck with Linux env(from scratch), no luck running it in Docker.

Anyone is working on this repo at all? what is the configs of your env?

Cheers.

**Comment by MichelDiz** [comment]
example of error

```
venus-ui-dev_1   | npm WARN tar ENOENT: no such file or directory, lstat '/usr/app/node_modules/.staging/@ant-design/icons-e49cc0bc/lib/fill'
venus-ui-dev_1   | npm WARN tar ENOENT: no such file or directory, open '/usr/app/node_modules/.staging/@ant-design/icons-e49cc0bc/lib/helpers.d.ts'
venus-ui-dev_1   | npm WARN tar ENOENT: no such file or directory, open '/usr/app/node_modules/.staging/@ant-design/icons-e49cc0bc/lib/helpers.js'
venus-ui-dev_1   | npm WARN tar ENOENT: no such file or directory, open '/usr/app/node_modules/.staging/@ant-design/icons-e49cc0bc/lib/index.d.ts'
venus-ui-dev_1   | 
venus-ui-dev_1   | npm ERR! A complete log of this run can be found in:
venus-ui-dev_1   | npm ERR!     /root/.npm/_logs/2022-01-23T00_40_22_382Z-debug.log
venus-ui-dev_1   | 
venus-ui-dev_1   | > venus@0.1.0 start /usr/app
venus-ui-dev_1   | > react-scripts --max_old_space_size=4096 start
venus-ui-dev_1   | 
venus-ui-dev_1   | sh: react-scripts: not found
venus-ui-dev_1   | npm ERR! code ELIFECYCLE
venus-ui-dev_1   | npm ERR! syscall spawn
venus-ui-dev_1   | npm ERR! file sh
venus-ui-dev_1   | npm ERR! errno ENOENT
venus-ui-dev_1   | npm ERR! venus@0.1.0 start: `react-scripts --max_old_space_size=4096 start`
venus-ui-dev_1   | npm ERR! spawn ENOENT
venus-ui-dev_1   | npm ERR! 
venus-ui-dev_1   | npm ERR! Failed at the venus@0.1.0 start script.
venus-ui-dev_1   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
venus-ui-dev_1   | 
venus-ui-dev_1   | npm ERR! A complete log of this run can be found in:
venus-ui-dev_1   | npm ERR!     /root/.npm/_logs/2022-01-23T00_40_23_961Z-debug.log
```


Erros during install

```
npm ERR! code 1
npm ERR! path /root/venus-protocol-interface/node_modules/node-sass
npm ERR! command failed
npm ERR! command sh -c node scripts/build.js
npm ERR! Building: /usr/bin/node /root/venus-protocol-interface/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   '/usr/bin/node',
npm ERR! gyp verb cli   '/root/venus-protocol-interface/node_modules/node-gyp/bin/node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@17.1.0 | linux | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/root/venus-protocol-interface/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/root/venus-protocol-interface/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/root/venus-protocol-interface/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (/root/venus-protocol-interface/node_modules/which/which.js:13:12)
npm ERR! gyp verb `which` failed     at F (/root/venus-protocol-interface/node_modules/which/which.js:68:19)
npm ERR! gyp verb `which` failed     at E (/root/venus-protocol-interface/node_modules/which/which.js:80:29)
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/which/which.js:89:16
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/isexe/index.js:42:5
npm ERR! gyp verb `which` failed     at /root/venus-protocol-interface/node_modules/isexe/mode.js:8:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python /usr/bin/python
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-01-23T00_57_29_315Z-debug.log
```

**Comment by JaimeDeFi** [comment]
I tried and no issues on Docker Desktop on Windows

**Comment by MichelDiz** [comment]
okay, would you share your steps? BTW, this project was made with Windows users in mind? Cuz not even on Linux it runs well.

BTW, I was trying the DEV part. The prod worked at some point.

**Comment by JaimeDeFi** [comment]
I did a fork on my github and wrote steps taken on Readme. It should work for you. 
Nop, I think Venus Team is working with Linux but somehow Readme is not really accurate.

**Comment by baomastr** [comment]
@MichelDiz try to use node v14 before installing packages and add .env file before start. It works on Mac os

**Comment by MichelDiz** [comment]
No luck, it runs the installation fine. But there is some babel(module paths) issue that I'm not sure how to identify.
![Screen Shot 2022-02-06 at 12 16 20](https://user-images.githubusercontent.com/6570955/152687688-82c2ef2d-9d0e-4a08-b521-9351b68e6645.png)

I had to downgrade vie a pkg https://nodejs.org/dist/latest-v14.x/


@baomastr do I have to add any data in that .env? (I know it isn't related to the error I get)

> NODE_PATH=
REACT_APP_CHAIN_ID=

**Comment by baomastr** [comment]
to resolve absolute paths you can use `NODE_PATH=./src` or use branch develop. there is already fixed this issue with tsConfig.json

**Comment by baomastr** [comment]
@MichelDiz 

to resolve absolute paths and request issues you can use current data in .env file
```
NODE_ENV=development
NODE_PATH=src/
#REACT_APP_CHAIN_ID should be 97 for testnet
REACT_APP_CHAIN_ID=97
``` 
or use branch develop. absolute paths issue is already fixed  there with tsConfig.json

it gonna be updated soon in readme and master branch

**Comment by MichelDiz** [comment]
Yep, that solved the issue! Thank you for the help!

Cheers!
